# Generated by Django 4.0.5 on 2022-06-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_key', models.CharField(max_length=50)),
                ('_url', models.CharField(max_length=50)),
                ('_active', models.BooleanField()),
                ('_created_date', models.DateTimeField(auto_now_add=True)),
                ('_modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
